### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by ViolentGlitcher** [ATLauncher/Website-Issues#68]
Every time I try to load any mod pack it just crashes.

Here is the console

[12/10/2015 20:53:06 PM] Console Cleared
[12/10/2015 20:53:09 PM] Logging into Minecraft!
[12/10/2015 20:53:10 PM] Trying to login with access token!
[12/10/2015 20:53:10 PM] Launching pack Yogscast Complete Pack 2.9.3.4-RR-YOGS for Minecraft 1.6.4
[12/10/2015 20:53:10 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre1.8.0_60\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Xms256M, -Xmx3072M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Djava.library.path=**USERSDIR**\Instances\YogscastCompletePack\bin\natives, -cp, **USERSDIR**\ATLauncher.jar;**USERSDIR**\Instances\YogscastCompletePack\jarmods\forge-1.6.4-9.11.1.965-universal.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\launchwrapper-1.8.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\asm-all-4.1.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\scala-compiler-2.10.2.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\scala-library-2.10.2.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\lzma-0.0.1.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\jopt-simple-4.5.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\liteloader-1.6.4.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\codecjorbis-20101023.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\codecwav-20101023.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\libraryjavasound-20101123.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\librarylwjglopenal-20100824.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\soundsystem-20120107.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\argo-2.25_fixed.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\bcprov-jdk15on-1.47.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\guava-14.0.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\commons-lang3-3.1.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\commons-io-2.4.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\jinput-2.0.5.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\jutils-1.0.0.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\gson-2.2.2.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\lwjgl-2.9.0.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\lwjgl_util-2.9.0.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\minecraft.jar, net.minecraft.launchwrapper.Launch, --username, REDACTED, --session, token:REDACTED:08beac44680e442da90fdbe613bcc240, --version, 1.6.4, --gameDir, **USERSDIR**\Instances\YogscastCompletePack, --assetsDir, **USERSDIR**\Configs\Resources\virtual\legacy, --width=854, --height=480, --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker, --tweakClass, com.mumfrey.liteloader.launch.LiteLoaderTweaker]
[12/10/2015 20:53:10 PM] Oct 12, 2015 8:53:10 PM net.minecraft.launchwrapper.LogWrapper log
[12/10/2015 20:53:10 PM] INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[12/10/2015 20:53:10 PM] Oct 12, 2015 8:53:10 PM net.minecraft.launchwrapper.LogWrapper log
[12/10/2015 20:53:10 PM] INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[12/10/2015 20:53:10 PM] Oct 12, 2015 8:53:10 PM net.minecraft.launchwrapper.LogWrapper log
[12/10/2015 20:53:10 PM] INFO: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[12/10/2015 20:53:10 PM] Oct 12, 2015 8:53:10 PM net.minecraft.launchwrapper.LogWrapper log
[12/10/2015 20:53:10 PM] INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[12/10/2015 20:53:11 PM] [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
[12/10/2015 20:53:11 PM] [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_60, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_60
[12/10/2015 20:53:11 PM] [WARNING] [ForgeModLoader] The coremod universalelectricity.core.UELoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:11 PM] [WARNING] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:11 PM] [INFO] [STDERR] Warning: version of ForgeMultipart-universal-1.6.4-, 1.0.1.268 is newer than request 1.0.0.244
[12/10/2015 20:53:11 PM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod worldcore.asm.WCFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [INFO] [ForgeModLoader] AMCore initializing...stand back!  I'm going to try MAGIC!
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [INFO] [ForgeModLoader] [AppEng] Core Init
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod biomesoplenty.asm.BOPFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod denoflionsx.denLib.CoreMod.denLibCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod denoflionsx.DenPipes.Core.DenPipesCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod chylex.java7check.JavaCheckerCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod openeye.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod denoflionsx.PluginsforForestry.Core.CoreMod.PfFCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod mrtjp.projectred.compatibility.CompatibilityCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod com.dynious.refinedrelocation.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod resonant.core.ResonantPluginLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [INFO] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR! *zap*
[12/10/2015 20:53:12 PM] [INFO] [TCon-Preloader] Constructing preloader (Modules: [tconstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])
[12/10/2015 20:53:12 PM] [INFO] [TCon-Preloader] Found a properties file. Attempting load...
[12/10/2015 20:53:12 PM] [INFO] [TCon-Preloader] Loaded properties successfully. Using specified settings.
[12/10/2015 20:53:12 PM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12/10/2015 20:53:12 PM] [INFO] [ForgeModLoader] Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[12/10/2015 20:53:12 PM] [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12/10/2015 20:53:12 PM] [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[12/10/2015 20:53:12 PM] [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12/10/2015 20:53:12 PM] [SEVERE] [ForgeModLoader] Unable to launch
[12/10/2015 20:53:12 PM] java.util.ConcurrentModificationException
[12/10/2015 20:53:12 PM] 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[12/10/2015 20:53:12 PM] 	at java.util.ArrayList$Itr.remove(Unknown Source)
[12/10/2015 20:53:12 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[12/10/2015 20:53:12 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[12/10/2015 20:53:13 PM] Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[12/10/2015 20:53:13 PM] Checking for updated files!
[12/10/2015 20:53:13 PM] No updates found!

**Comment by RyanTheAllmighty** [comment]
All issues go to http://forums.atlauncher.com/
